
#had claude help make this, hopefull it works
name: Build LWJGL Project
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'  # Built-in Maven caching
        
    - name: Run Tests
      run: mvn test
        
    - name: Build with All LWJGL Natives
      if: success()  # Only run if tests pass
      run: |
        # Build once with all natives profiles activated
        mvn clean package \
          -P lwjgl-natives-windows-aarch64,\
          lwjgl-natives-windows-amd64,\
          lwjgl-natives-windows-x86,\
          lwjgl-natives-linux-amd64,\
          lwjgl-natives-linux-aarch64,\
          lwjgl-natives-linux-arm,\
          lwjgl-natives-linux-arm32,\
          lwjgl-natives-macos-x86_64,\
          lwjgl-natives-macos-aarch64
          
    - name: Upload Build Artifacts
      if: success()  # Only run if both tests and build pass
      uses: actions/upload-artifact@v4
      with:
        name: lwjgl-build
        path: target/*.jar
